### PR TITLE
#18 Fix bug with null member ID's being added to database

### LINKED ISSUE #18: Adding a new member creates a null ID field
Check `MongoRepository` to find out why this is and fix, and also delete past members with `null` id's

### PR DESCRIPTION
**Pull request by Ray-F**
Fixes #18

### CODE REVIEW

File: server/models/mongodb/MongoRepository.js [hunk 1]
```diff
@@ -23,23 +23,26 @@ const getMembersFromDb = async (memberId = null) => {
 }
 
 /**
- * Saves a member to the database.
+ * Saves a `memberObject` to the database.
+ *
```
Comment (Mykhol) [inline server/models/mongodb/MongoRepository.js:27]: Is having a space between these comments necessary?

**Review by Mykhol — APPROVED** [review]

File: server/models/mongodb/MongoRepository.js (hunk 1 above)
Comment (Ray-F) [reply server/models/mongodb/MongoRepository.js:27]: Good point! Let's combine those together.
